name: changed files

on:
  push:
    branches:
      - main
    paths:
      - dir-1/**
      - dir-2/**
      - dir-3/**

jobs:
  changed_files:
    name: Get all changed files
    runs-on: ubuntu-latest
    
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10

  build:
    needs: changed_files
    
    name: Test changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - var1: dir-1/
            var2: var2a
          - var1: dir-2/
            var2: var2b
          - var1: dir-3/
            var2: var2c
    
    steps:
      if: contains(needs.changed_files.changed-files.outputs.all_changed_and_modified_files, matrix.var1)
      - uses: actions/checkout@v2

      - name: if changed in specific dir
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was added for ${{ matrix.var1 }}"
          done

      - name: jist another run
        run: |
          echo "heyyyyy"
