name: changed files

on:
  push:
    branches:
      - main
    paths:
      - dir-1/**
      - dir-2/**
      - dir-3/**

jobs:
  build-and-push:
    name: Test changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - var1: dir-1/
            var2: var2a
          - var1: dir-2/
            var2: var2b
          - var1: dir-3/
            var2: var2c
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.community/t/can-i-process-only-changed-files-with-github-actions/137814
      - name: Get changed files
        shell: bash
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
          echo "::set-env name=changed_files::${changed_files}"

      - name: echo
        run: |
          echo "$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})"

      - name: print relevant changed files
        if: contains(env.changed_files, matrix.var1)
        run: |
          for file in ${{ env.changed_files }}; do
            echo "$file was added for ${{ matrix.var1 }}"
          done

      - name: just another run
        if: contains(env.changed_files, matrix.var1)
        run: |
          echo "heyyyyy"
